import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {DndContext,PointerSensor,useSensor,useSensors,closestCenter,useDroppable} from "@dnd-kit/core";
import {SortableContext,useSortable,arrayMove,verticalListSortingStrategy} from "@dnd-kit/sortable";
import {CSS} from "@dnd-kit/utilities";
import {LayoutDashboard,FolderKanban,Lightbulb,ListTodo,ShoppingCart,Film,Plus,GripVertical,X,Trash2,ExternalLink,Download,Upload,ChevronRight} from "lucide-react";
import "./style.css";

const CATS=["Personal","Business","Hobby","KB Garage","Eden GMC","Life","Other"];
const BUCKETS=[["today","Today"],["week","This Week"],["month","Next Month"],["backlog","Backlog"]];
const seed={
projects:[
{id:"p1",name:"KB Garage — First Build Video",category:"KB Garage",status:"Active",priority:1,progress:30,description:"Build the first repeatable KB Garage project and content workflow.",notion:"",contentType:"YouTube Video",videoStyle:"Workshop documentary: practical, clean, mechanical and direct.",script:"Hook:\\n\\nIntro:\\n\\nMain build:\\n\\nResult:\\n\\nOutro:",thumbnail:"",editing:"",shots:[{id:"s1",text:"Garage establishing shot",done:false},{id:"s2",text:"Workbench / project reveal",done:false}]},
{id:"p2",name:"Eden GMC Website",category:"Eden GMC",status:"Active",priority:2,progress:60,description:"Website improvements and lead generation.",notion:"",contentType:"",videoStyle:"",script:"",thumbnail:"",editing:"",shots:[]},
{id:"p3",name:"Direct-Drive Wheel",category:"Hobby",status:"Planned",priority:3,progress:10,description:"Direct-drive steering wheel build.",notion:"",contentType:"",videoStyle:"",script:"",thumbnail:"",editing:"",shots:[]}],
tasks:[
{id:"t1",title:"Plan KB Garage first video",projectId:"p1",bucket:"today",position:1,done:false,details:""},
{id:"t2",title:"Fix Eden GMC contact flow",projectId:"p2",bucket:"week",position:1,done:false,details:""},
{id:"t3",title:"Research motor controller",projectId:"p3",bucket:"month",position:1,done:false,details:""}],
purchases:[
{id:"b1",name:"Camera microphone",projectId:"p1",status:"Need",blocking:true,qty:1,cost:0,url:"",position:1},
{id:"b2",name:"Tripod / camera mount",projectId:"p1",status:"Need",blocking:false,qty:1,cost:0,url:"",position:2},
{id:"b3",name:"Motor controller",projectId:"p3",status:"Need",blocking:true,qty:1,cost:0,url:"",position:1},
{id:"b4",name:"48V PSU",projectId:"p3",status:"Need",blocking:true,qty:1,cost:0,url:"",position:2}],
ideas:[{id:"i1",title:"Permanent KB Garage filming corner",category:"KB Garage"},{id:"i2",title:"Eden GMC before/after series",category:"Eden GMC"}]
};
const KEY="project-hq-full-v1";
const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}}
function Sortable({id,children,className=""}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.45:1}} className={className}>{children({attributes,listeners})}</div>}
function Drop({id,children}){const {setNodeRef,isOver}=useDroppable({id});return <div ref={setNodeRef} className={"drop "+(isOver?"over":"")}>{children}</div>}

function App(){
const [d,setD]=useState(load),[page,setPage]=useState("Dashboard"),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[filter,setFilter]=useState("All");
useEffect(()=>localStorage.setItem(KEY,JSON.stringify(d)),[d]);
const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:5}}));
const projects=[...d.projects].sort((a,b)=>a.priority-b.priority);
const pmap=Object.fromEntries(d.projects.map(p=>[p.id,p]));
const queue=[...d.purchases].filter(x=>x.status==="Need").sort((a,b)=>(pmap[a.projectId]?.priority??999)-(pmap[b.projectId]?.priority??999)||(b.blocking-a.blocking)||a.position-b.position);
function projectDrag({active,over}){if(!over||active.id===over.id)return;setD(x=>{let a=[...x.projects].sort((m,n)=>m.priority-n.priority);let oi=a.findIndex(z=>z.id===active.id),ni=a.findIndex(z=>z.id===over.id);if(oi<0||ni<0)return x;a=arrayMove(a,oi,ni).map((z,i)=>({...z,priority:i+1}));return {...x,projects:a}})}
function taskDrag({active,over}){if(!over)return;setD(x=>{let tasks=[...x.tasks],i=tasks.findIndex(t=>t.id===active.id);if(i<0)return x;let target=tasks.find(t=>t.id===over.id);let bucket=BUCKETS.some(b=>b[0]===over.id)?over.id:target?.bucket;if(!bucket)return x;let moved={...tasks[i],bucket};tasks.splice(i,1);let bucketItems=tasks.filter(t=>t.bucket===bucket);let overIndex=target?bucketItems.findIndex(t=>t.id===target.id):bucketItems.length;let globalInsert=overIndex>=bucketItems.length?tasks.length:tasks.findIndex(t=>t.id===bucketItems[overIndex]?.id);if(globalInsert<0)globalInsert=tasks.length;tasks.splice(globalInsert,0,moved);BUCKETS.forEach(([b])=>{let n=0;tasks=tasks.map(t=>t.bucket===b?{...t,position:++n}:t)});return {...x,tasks}})}
function saveProject(p){setD(x=>({...x,projects:x.projects.map(q=>q.id===p.id?p:q)}));setSelected(p)}
function delProject(id){setD(x=>({...x,projects:x.projects.filter(p=>p.id!==id),tasks:x.tasks.filter(t=>t.projectId!==id),purchases:x.purchases.filter(b=>b.projectId!==id)}));setSelected(null)}
function exportJSON(){let blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="project-hq-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importJSON(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{setD(JSON.parse(r.result))}catch{alert("Invalid Project HQ JSON")}};r.readAsText(f)}
return <div className="app"><aside><div className="brand"><b>HQ</b><span><strong>PROJECT HQ</strong><small>Ideas → Projects → Done</small></span></div>{[[LayoutDashboard,"Dashboard"],[FolderKanban,"Projects"],[Lightbulb,"Ideas"],[ListTodo,"To-Do"],[ShoppingCart,"Purchases"],[Film,"Content"]].map(([I,n])=><button key={n} className={page===n?"nav on":"nav"} onClick={()=>setPage(n)}><I size={18}/>{n}</button>)}<div className="sidebottom"><button onClick={exportJSON}><Download size={15}/> Backup</button><label><Upload size={15}/> Restore<input type="file" accept=".json" onChange={importJSON}/></label></div></aside>
<main><header><div><small>PROJECT COMMAND CENTRE</small><h1>{page}</h1></div><button className="primary" onClick={()=>setModal(page==="Ideas"?"idea":page==="To-Do"?"task":page==="Purchases"?"buy":"project")}><Plus size={17}/> Add</button></header>
{page==="Dashboard"&&<Dashboard d={d} projects={projects} queue={queue} pmap={pmap} open={setSelected}/>}
{page==="Projects"&&<Projects projects={projects} filter={filter} setFilter={setFilter} sensors={sensors} drag={projectDrag} open={setSelected}/>}
{page==="Ideas"&&<Ideas d={d} setD={setD}/>}
{page==="To-Do"&&<Tasks d={d} setD={setD} sensors={sensors} drag={taskDrag} pmap={pmap}/>}
{page==="Purchases"&&<Purchases d={d} setD={setD} queue={queue} pmap={pmap}/>}
{page==="Content"&&<Content d={d} open={setSelected}/>}
{modal&&<Add type={modal} close={()=>setModal(null)} d={d} setD={setD}/>}
{selected&&<Detail p={d.projects.find(x=>x.id===selected.id)||selected} d={d} setD={setD} save={saveProject} close={()=>setSelected(null)} del={delProject}/>}
</main></div>
}

const Card=({title,children})=><section className="card"><h2>{title}</h2>{children}</section>;
function PRow({p,open,drag}){return <button className="prow" onClick={()=>open(p)}><span {...drag} onClick={e=>e.stopPropagation()} className="grip"><GripVertical size={17}/></span><b>#{p.priority}</b><div><strong>{p.name}</strong><small>{p.category} · {p.status}</small><i><em style={{width:p.progress+"%"}}/></i></div><span>{p.progress}%</span><ChevronRight size={17}/></button>}
function Dashboard({d,projects,queue,pmap,open}){let today=d.tasks.filter(t=>t.bucket==="today"&&!t.done);return <><div className="stats">{[[projects.length,"Projects"],[projects.filter(p=>p.status==="Active").length,"Active"],[d.tasks.filter(t=>!t.done).length,"Open tasks"],[queue.length,"Need to buy"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="two"><Card title="🔥 Today">{today.map(t=><p className="line" key={t.id}>{t.title}<small>{pmap[t.projectId]?.name||"General"}</small></p>)}</Card><Card title="📌 Project Priority">{projects.slice(0,5).map(p=><PRow key={p.id} p={p} open={open} drag={{}}/>)}</Card></div><Card title="🛒 Purchase Queue">{queue.slice(0,8).map(b=><p className="buyline" key={b.id}><span className={b.blocking?"red":""}/><b>{b.name}</b><small>{pmap[b.projectId]?.name}</small><em>#{pmap[b.projectId]?.priority}</em></p>)}</Card></>}
function Projects({projects,filter,setFilter,sensors,drag,open}){let shown=projects.filter(p=>filter==="All"||p.category===filter);return <><div className="filters">{["All",...CATS].map(c=><button className={filter===c?"chip on":"chip"} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={shown.map(p=>p.id)} strategy={verticalListSortingStrategy}>{shown.map(p=><Sortable id={p.id} key={p.id}>{h=><PRow p={p} open={open} drag={{...h.attributes,...h.listeners}}/>}</Sortable>)}</SortableContext></DndContext></>}
function Ideas({d,setD}){return <div className="tiles">{d.ideas.map(i=><Card key={i.id} title={i.title}><span className="tag">{i.category}</span><button className="danger mini" onClick={()=>setD(x=>({...x,ideas:x.ideas.filter(z=>z.id!==i.id)}))}><Trash2 size={14}/> Delete</button></Card>)}</div>}
function Tasks({d,setD,sensors,drag,pmap}){function toggle(id){setD(x=>({...x,tasks:x.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}))}return <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={drag}><div className="board">{BUCKETS.map(([id,label])=>{let ts=d.tasks.filter(t=>t.bucket===id).sort((a,b)=>a.position-b.position);return <Drop id={id} key={id}><section className="col"><h3>{label}<span>{ts.filter(t=>!t.done).length}</span></h3><SortableContext items={ts.map(t=>t.id)} strategy={verticalListSortingStrategy}>{ts.map(t=><Sortable id={t.id} key={t.id}>{h=><article className={t.done?"task done":"task"}><span {...h.attributes} {...h.listeners} className="grip"><GripVertical size={15}/></span><input type="checkbox" checked={t.done} onChange={()=>toggle(t.id)}/><div><b>{t.title}</b><small>{pmap[t.projectId]?.name||"General"}</small></div><button onClick={()=>setD(x=>({...x,tasks:x.tasks.filter(q=>q.id!==t.id)}))}><X size={13}/></button></article>}</Sortable>)}</SortableContext></section></Drop>})}</div></DndContext>}
function Purchases({d,setD,queue,pmap}){return <Card title="Prioritised Purchase Queue">{queue.map(b=><div className="purchase" key={b.id}><div><b>{b.name}</b><small>{pmap[b.projectId]?.name} · Qty {b.qty}</small></div><label><input type="checkbox" checked={b.blocking} onChange={e=>setD(x=>({...x,purchases:x.purchases.map(q=>q.id===b.id?{...q,blocking:e.target.checked}:q)}))}/> Blocking</label><input type="number" value={b.cost} min="0" step=".01" onChange={e=>setD(x=>({...x,purchases:x.purchases.map(q=>q.id===b.id?{...q,cost:+e.target.value}:q)}))}/><select value={b.status} onChange={e=>setD(x=>({...x,purchases:x.purchases.map(q=>q.id===b.id?{...q,status:e.target.value}:q)}))}>{["Need","Ordered","Received","Installed"].map(s=><option key={s}>{s}</option>)}</select>{b.url&&<a href={b.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a>}<button onClick={()=>setD(x=>({...x,purchases:x.purchases.filter(q=>q.id!==b.id)}))}><Trash2 size={14}/></button></div>)}</Card>}
function Content({d,open}){let ps=d.projects.filter(p=>p.category==="KB Garage"||p.contentType);return <><p className="intro">Content projects keep high-level priority in Project HQ while scripts, shots and production details can live here or in a linked Notion workspace.</p><div className="tiles">{ps.map(p=><button className="content" onClick={()=>open(p)} key={p.id}><span className="tag">{p.category}</span><h2>{p.name}</h2><div className="contentgrid"><span>🎨 Video Style</span><span>🎥 Shots</span><span>✅ Checklist</span><span>📝 Script</span><span>🖼️ Thumbnail</span><span>✂️ Editing</span></div>{p.notion&&<b>↗ Notion linked</b>}</button>)}</div></>}

function Add({type,close,d,setD}){let isP=type==="project",isT=type==="task",isB=type==="buy";const [v,setV]=useState(isP?{name:"",category:"Personal",status:"Idea"}:isT?{title:"",projectId:"",bucket:"today"}:isB?{name:"",projectId:d.projects[0]?.id||"",qty:1,cost:0,url:"",blocking:false}:{title:"",category:"Personal"});function go(){if(!(v.name||v.title))return;if(isP){let p={...v,id:uid("p"),priority:d.projects.length+1,progress:0,description:"",notion:"",contentType:"",videoStyle:"",script:"",thumbnail:"",editing:"",shots:[]};setD(x=>({...x,projects:[...x.projects,p]}))}else if(isT)setD(x=>({...x,tasks:[...x.tasks,{...v,id:uid("t"),position:x.tasks.filter(t=>t.bucket===v.bucket).length+1,done:false,details:""}]}));else if(isB)setD(x=>({...x,purchases:[...x.purchases,{...v,id:uid("b"),status:"Need",position:x.purchases.filter(b=>b.projectId===v.projectId).length+1}]}));else setD(x=>({...x,ideas:[...x.ideas,{...v,id:uid("i")}]}));close()}return <div className="shade"><div className="modal"><button className="x" onClick={close}><X/></button><h2>Add {isP?"Project":isT?"Task":isB?"Purchase":"Idea"}</h2><label>{isP||isB?"Name":isT?"Task":"Idea"}<input autoFocus value={v.name??v.title} onChange={e=>setV({...v,[v.name!==undefined?"name":"title"]:e.target.value})}/></label>{(isP||(!isT&&!isB))&&<label>Category<select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label>}{isP&&<label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{["Idea","Planned","Active","Paused","Complete"].map(s=><option key={s}>{s}</option>)}</select></label>}{(isT||isB)&&<label>Project<select value={v.projectId} onChange={e=>setV({...v,projectId:e.target.value})}><option value="">General</option>{d.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>}{isT&&<label>When<select value={v.bucket} onChange={e=>setV({...v,bucket:e.target.value})}>{BUCKETS.map(b=><option value={b[0]} key={b[0]}>{b[1]}</option>)}</select></label>}{isB&&<><label>Quantity<input type="number" min="1" value={v.qty} onChange={e=>setV({...v,qty:+e.target.value})}/></label><label>Estimated cost<input type="number" min="0" step=".01" value={v.cost} onChange={e=>setV({...v,cost:+e.target.value})}/></label><label>Product URL<input value={v.url} onChange={e=>setV({...v,url:e.target.value})}/></label><label className="check"><input type="checkbox" checked={v.blocking} onChange={e=>setV({...v,blocking:e.target.checked})}/> Blocking purchase</label></>}<button className="primary full" onClick={go}>Create</button></div></div>}
function Detail({p,d,setD,save,close,del}){const [v,setV]=useState({...p});function shotAdd(){setV(x=>({...x,shots:[...x.shots,{id:uid("s"),text:"New shot",done:false}]}))}return <div className="shade"><div className="drawer"><button className="x" onClick={close}><X/></button><span className="tag">{v.category}</span><input className="title" value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><div className="meta"><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{["Idea","Planned","Active","Paused","Complete"].map(s=><option key={s}>{s}</option>)}</select></label><label>Category<select value={v.category} onChange={e=>setV({...v,category:e.target.value})}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" value={v.progress} onChange={e=>setV({...v,progress:+e.target.value})}/></label></div><label>Description<textarea rows="3" value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label>
<section><h2>Tasks</h2>{d.tasks.filter(t=>t.projectId===v.id).map(t=><p className="line" key={t.id}>{t.title}<small>{BUCKETS.find(b=>b[0]===t.bucket)?.[1]}</small></p>)}</section><section><h2>Parts / Purchases</h2>{d.purchases.filter(b=>b.projectId===v.id).map(b=><p className="line" key={b.id}>{b.name}<small>{b.status}</small></p>)}</section>
{(v.category==="KB Garage"||v.contentType)&&<section><h2>🎬 Content Workspace</h2><label>Content type<select value={v.contentType} onChange={e=>setV({...v,contentType:e.target.value})}><option value="">Not content</option><option>YouTube Video</option><option>Short / Reel</option><option>Series</option><option>Other</option></select></label><label>Notion shared link<input placeholder="https://www.notion.so/..." value={v.notion} onChange={e=>setV({...v,notion:e.target.value})}/></label>{v.notion&&<a className="primary notion" href={v.notion} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Open Notion</a>}<label>Video style<textarea rows="3" value={v.videoStyle} onChange={e=>setV({...v,videoStyle:e.target.value})}/></label><label>Script<textarea rows="10" value={v.script} onChange={e=>setV({...v,script:e.target.value})}/></label><label>Thumbnail notes<textarea rows="3" value={v.thumbnail} onChange={e=>setV({...v,thumbnail:e.target.value})}/></label><label>Editing notes<textarea rows="3" value={v.editing} onChange={e=>setV({...v,editing:e.target.value})}/></label><div className="sectionhead"><h2>Shot checklist</h2><button onClick={shotAdd}><Plus size={14}/> Add shot</button></div>{v.shots.map((s,i)=><div className="shot" key={s.id}><input type="checkbox" checked={s.done} onChange={e=>{let a=[...v.shots];a[i]={...s,done:e.target.checked};setV({...v,shots:a})}}/><input value={s.text} onChange={e=>{let a=[...v.shots];a[i]={...s,text:e.target.value};setV({...v,shots:a})}}/><button onClick={()=>setV({...v,shots:v.shots.filter(q=>q.id!==s.id)})}><X size={13}/></button></div>)}</section>}
<div className="draweractions"><button className="danger" onClick={()=>confirm("Delete this project and its tasks/purchases?")&&del(v.id)}><Trash2 size={15}/> Delete</button><button className="primary" onClick={()=>save(v)}>Save Project</button></div></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
